name: shopper
description: "Shopping App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  google_fonts: ^6.1.0
  firebase_auth: ^5.5.2
  barcode_scan2: ^4.5.1
  easy_upi_payment: ^0.1.6
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/gpay.png
    - assets/images/phonepe.png
    - assets/images/paytm.png
